version: "3.8"
services:
  postgres:
    image: postgres
    environment:
     # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tools-version
    ports:
      - "5432:5432"

  postgres_admin:
    image: dpage/pgadmin4:6.12
    container_name: postgres_admin
    depends_on:
    - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
    - "5050:80"