INSERT INTO project (id, name) VALUES (1, 'wired');
INSERT INTO project (id, name) VALUES (2, 'commons');
INSERT INTO project (id, name) VALUES (3, 'rces');
INSERT INTO project (id, name) VALUES (4, 'refclient');
INSERT INTO project (id, name) VALUES (5, 'rleads');
INSERT INTO project (id, name) VALUES (6, 'rconnect');
INSERT INTO project (id, name) VALUES (7, 'configurater');
INSERT INTO project (id, name) VALUES (8, 'uci');
INSERT INTO project (id, name) VALUES (9, 'myr');
INSERT INTO project (id, name) VALUES (10, 'rdoc');
INSERT INTO project (id, name) VALUES (11, 'artimis');
INSERT INTO project (id, name) VALUES (12, 'one');

INSERT INTO repository (id, icon, name, percentage) VALUES (1, NULL, 'gitlab-dashboard', 95);
INSERT INTO repository (id, icon, name, percentage) VALUES (2, NULL, 'backoffice-styleguide', 15);
INSERT INTO repository (id, icon, name, percentage) VALUES (3, NULL, 'karate-gatling', 55);
INSERT INTO repository (id, icon, name, percentage) VALUES (4, NULL, 'swagger-ui', 19);
INSERT INTO repository (id, icon, name, percentage) VALUES (6, NULL, 'wired-lambda-awsbatchincoming', 17);
INSERT INTO repository (id, icon, name, percentage) VALUES (5, NULL, 'test-auto-ui-cypress', 19);
INSERT INTO repository (id, icon, name, percentage) VALUES (7, NULL, 'wired-backoffice-i18', 78);
INSERT INTO repository (id, icon, name, percentage) VALUES (8, NULL, 'wired-backoffice-energy-getway', 65);
INSERT INTO repository (id, icon, name, percentage) VALUES (9, NULL, 'wired-backoffice-cei', 25);
INSERT INTO repository (id, icon, name, percentage) VALUES (10, NULL, 'wired-npm-rest-client', 15);
INSERT INTO repository (id, icon, name, percentage) VALUES (11, NULL, 'wired-npm-rest-client', 15);
INSERT INTO repository (id, icon, name, percentage) VALUES (12, NULL, 'new-repo-alpha', 45);
INSERT INTO repository (id, icon, name, percentage) VALUES (13, NULL, 'new-repo-beta', 62);
INSERT INTO repository (id, icon, name, percentage) VALUES (14, NULL, 'new-repo-gamma', 33);
INSERT INTO repository (id, icon, name, percentage) VALUES (15, NULL, 'new-repo-delta', 84);
INSERT INTO repository (id, icon, name, percentage) VALUES (16, NULL, 'new-repo-epsilon', 71);
INSERT INTO repository (id, icon, name, percentage) VALUES (17, NULL, 'new-repo-zeta', 57);
INSERT INTO repository (id, icon, name, percentage) VALUES (18, NULL, 'new-repo-eta', 29);
INSERT INTO repository (id, icon, name, percentage) VALUES (19, NULL, 'new-repo-theta', 49);
INSERT INTO repository (id, icon, name, percentage) VALUES (20, NULL, 'new-repo-iota', 88);
INSERT INTO repository (id, icon, name, percentage) VALUES (21, NULL, 'new-repo-kappa', 23);
INSERT INTO repository (id, icon, name, percentage) VALUES (22, NULL, 'new-repo-lambda', 54);
INSERT INTO repository (id, icon, name, percentage) VALUES (23, NULL, 'new-repo-mu', 38);
INSERT INTO repository (id, icon, name, percentage) VALUES (24, NULL, 'new-repo-nu', 64);
INSERT INTO repository (id, icon, name, percentage) VALUES (25, NULL, 'new-repo-xi', 12);
INSERT INTO repository (id, icon, name, percentage) VALUES (26, NULL, 'new-repo-omicron', 76);
INSERT INTO repository (id, icon, name, percentage) VALUES (27, NULL, 'new-repo-pi', 32);
INSERT INTO repository (id, icon, name, percentage) VALUES (28, NULL, 'new-repo-rho', 44);
INSERT INTO repository (id, icon, name, percentage) VALUES (29, NULL, 'new-repo-sigma', 90);
INSERT INTO repository (id, icon, name, percentage) VALUES (30, NULL, 'new-repo-tau', 50);
INSERT INTO repository (id, icon, name, percentage) VALUES (31, NULL, 'new-repo-upsilon', 27);
INSERT INTO repository (id, icon, name, percentage) VALUES (32, NULL, 'new-repo-phi', 83);
INSERT INTO repository (id, icon, name, percentage) VALUES (33, NULL, 'new-repo-chi', 39);
INSERT INTO repository (id, icon, name, percentage) VALUES (34, NULL, 'new-repo-psi', 72);
INSERT INTO repository (id, icon, name, percentage) VALUES (35, NULL, 'new-repo-omega', 11);
INSERT INTO repository (id, icon, name, percentage) VALUES (36, NULL, 'new-repo-alpha1', 65);
INSERT INTO repository (id, icon, name, percentage) VALUES (37, NULL, 'new-repo-beta1', 48);
INSERT INTO repository (id, icon, name, percentage) VALUES (38, NULL, 'new-repo-gamma1', 18);
INSERT INTO repository (id, icon, name, percentage) VALUES (39, NULL, 'new-repo-delta1', 97);
INSERT INTO repository (id, icon, name, percentage) VALUES (40, NULL, 'new-repo-epsilon1', 30);
INSERT INTO repository (id, icon, name, percentage) VALUES (41, NULL, 'new-repo-zeta1', 85);
INSERT INTO repository (id, icon, name, percentage) VALUES (42, NULL, 'new-repo-eta1', 21);
INSERT INTO repository (id, icon, name, percentage) VALUES (43, NULL, 'new-repo-theta1', 77);
INSERT INTO repository (id, icon, name, percentage) VALUES (44, NULL, 'new-repo-iota1', 42);
INSERT INTO repository (id, icon, name, percentage) VALUES (45, NULL, 'new-repo-kappa1', 91);
INSERT INTO repository (id, icon, name, percentage) VALUES (46, NULL, 'new-repo-lambda1', 58);
INSERT INTO repository (id, icon, name, percentage) VALUES (47, NULL, 'new-repo-mu1', 34);
INSERT INTO repository (id, icon, name, percentage) VALUES (48, NULL, 'new-repo-nu1', 61);
INSERT INTO repository (id, icon, name, percentage) VALUES (49, NULL, 'new-repo-xi1', 26);
INSERT INTO repository (id, icon, name, percentage) VALUES (50, NULL, 'new-repo-omicron1', 86);
INSERT INTO repository (id, icon, name, percentage) VALUES (51, NULL, 'new-repo-pi1', 15);
INSERT INTO repository (id, icon, name, percentage) VALUES (52, NULL, 'new-repo-rho1', 68);
INSERT INTO repository (id, icon, name, percentage) VALUES (53, NULL, 'new-repo-sigma1', 31);
INSERT INTO repository (id, icon, name, percentage) VALUES (54, NULL, 'new-repo-tau1', 74);
INSERT INTO repository (id, icon, name, percentage) VALUES (55, NULL, 'new-repo-upsilon1', 25);
INSERT INTO repository (id, icon, name, percentage) VALUES (56, NULL, 'new-repo-phi1', 89);
INSERT INTO repository (id, icon, name, percentage) VALUES (57, NULL, 'new-repo-chi1', 47);
INSERT INTO repository (id, icon, name, percentage) VALUES (58, NULL, 'new-repo-psi1', 19);
INSERT INTO repository (id, icon, name, percentage) VALUES (59, NULL, 'new-repo-omega1', 82);
INSERT INTO repository (id, icon, name, percentage) VALUES (60, NULL, 'new-repo-alpha2', 35);
INSERT INTO repository (id, icon, name, percentage) VALUES (61, NULL, 'new-repo-beta2', 59);
INSERT INTO repository (id, icon, name, percentage) VALUES (62, NULL, 'new-repo-gamma2', 17);
INSERT INTO repository (id, icon, name, percentage) VALUES (63, NULL, 'new-repo-delta2', 96);
INSERT INTO repository (id, icon, name, percentage) VALUES (64, NULL, 'new-repo-epsilon2', 40);
INSERT INTO repository (id, icon, name, percentage) VALUES (65, NULL, 'new-repo-zeta2', 53);
INSERT INTO repository (id, icon, name, percentage) VALUES (66, NULL, 'new-repo-eta2', 22);
INSERT INTO repository (id, icon, name, percentage) VALUES (67, NULL, 'new-repo-theta2', 78);
INSERT INTO repository (id, icon, name, percentage) VALUES (68, NULL, 'new-repo-iota2', 24);
INSERT INTO repository (id, icon, name, percentage) VALUES (69, NULL, 'new-repo-kappa2', 92);
INSERT INTO repository (id, icon, name, percentage) VALUES (70, NULL, 'new-repo-lambda2', 66);
INSERT INTO repository (id, icon, name, percentage) VALUES (71, NULL, 'new-repo-mu2', 37);
INSERT INTO repository (id, icon, name, percentage) VALUES (72, NULL, 'new-repo-nu2', 70);
INSERT INTO repository (id, icon, name, percentage) VALUES (73, NULL, 'new-repo-xi2', 13);
INSERT INTO repository (id, icon, name, percentage) VALUES (74, NULL, 'new-repo-omicron2', 81);
INSERT INTO repository (id, icon, name, percentage) VALUES (75, NULL, 'new-repo-pi2', 20);
INSERT INTO repository (id, icon, name, percentage) VALUES (76, NULL, 'new-repo-pi2', 20);
INSERT INTO repository (id, icon, name, percentage) VALUES (77, NULL, 'new-repo-rho2', 60);


INSERT INTO dependency (id, icon, name, usage) VALUES (1, NULL, '@angular-builders/custom-webpack', 1);
INSERT INTO dependency (id, icon, name, usage) VALUES (2, NULL, '@angular-builders/jest', 4);
INSERT INTO dependency (id, icon, name, usage) VALUES (3, NULL, '@angular-devkit/build-angular', 21);
INSERT INTO dependency (id, icon, name, usage) VALUES (4, NULL, '@angular-devkit/ng-packagr', 1);
INSERT INTO dependency (id, icon, name, usage) VALUES (5, NULL, '@angular-devkit/schematics', 1);
INSERT INTO dependency (id, icon, name, usage) VALUES (6, NULL, '@angular-eslint/builder', 20);
INSERT INTO dependency (id, icon, name, usage) VALUES (7, NULL, '@angular-eslint/eslint-plugin', 17);
INSERT INTO dependency (id, icon, name, usage) VALUES (8, NULL, '@angular-eslint/eslint-plugin-template', 17); -- Fixed typo in name
INSERT INTO dependency (id, icon, name, usage) VALUES (9, NULL, '@angular-eslint/schematics', 19);
INSERT INTO dependency (id, icon, name, usage) VALUES (10, NULL, '@angular-eslint/template-parser', 19);
INSERT INTO dependency (id, icon, name, usage) VALUES (11, NULL, '@angular/animations', 25);

